# ============================================
# CONFIGURAÇÕES GERAIS DO SERVIDOR
# ============================================
server:
  port: 8080
  servlet:
    context-path: /crypto-monitor

spring:
  application:
    name: crypto-monitor

  # ============================================
  # CONFIGURAÇÃO DO BANCO DE DADOS
  # ============================================
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/crypto_monitor}
    driver-class-name: org.postgresql.Driver
    username: ${SPRING_DATASOURCE_USERNAME:crypto_user}
    password: ${SPRING_DATASOURCE_PASSWORD:qwe123}

  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    defer-datasource-initialization: false

  database-platform: org.hibernate.dialect.PostgreSQLDialect

  # ============================================
  # MIGRAÇÕES (FLYWAY)
  # ============================================
  flyway:
    enabled: true
    locations: classpath:db/migration
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/crypto_monitor}
    user: ${SPRING_DATASOURCE_USERNAME:crypto_user}
    password: ${SPRING_DATASOURCE_PASSWORD:qwe123}
    baseline-on-migrate: true
    validate-on-migrate: true
    out-of-order: false

  # ============================================
  # CONFIGURAÇÃO DE JWT
  # ============================================
  jwt:
    secret: ${JWT_SECRET:crypto-monitor-super-secret-key-that-should-be-changed-in-production-environment}
    expiration: ${JWT_EXPIRATION:86400000} # 24 horas

  # ============================================
  # CONFIGURAÇÃO DE EMAIL
  # ============================================
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME:andremendoncaolv@gmail.com}
    password: ${MAIL_PASSWORD:vjaljbffpdgpcscx}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            trust: smtp.gmail.com
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

  # ============================================
  # TAREFAS AGENDADAS (DESABILITADAS)
  # ============================================
  task:
    scheduling:
      enabled: false

# ============================================
# CONFIGURAÇÕES ESPECÍFICAS DA APLICAÇÃO
# ============================================
crypto:
  coins: bitcoin,ethereum,cardano,polkadot,chainlink,solana,avalanche-2,polygon,litecoin,bitcoin-cash

# ============================================
# ALERTAS AUTOMÁTICOS
# ============================================
alert:
  buy:
    threshold: -1.0
  sell:
    threshold: 1.0
  check-interval: 300000

# ============================================
# NOTIFICAÇÕES
# ============================================
notification:
  email:
    enabled: true
    from-name: Crypto Monitoring System
    from: ${MAIL_USERNAME:andremendoncaolv@gmail.com}
    cooldown-minutes: 30

  telegram:
    enabled: ${TELEGRAM_ENABLED:false}
    bot-token: ${TELEGRAM_BOT_TOKEN:}
    chat-id: ${TELEGRAM_CHAT_ID:}

# ============================================
# SISTEMA DE MONITORAMENTO
# ============================================
monitoring:
  max-concurrent-users: 50
  thread-pool-size: 10
  shutdown-timeout: 60

# ============================================
# API COINGECKO
# ============================================
coingecko:
  api:
    url: https://api.coingecko.com/api/v3
  rate-limit: 30

# ============================================
# LOGS
# ============================================
logging:
  level:
    com.crypto: INFO
    com.crypto.service.MonitoringControlService: DEBUG
    org.springframework.web: DEBUG
    org.springframework.mail: DEBUG
    org.flywaydb: DEBUG
    org.springframework.scheduling: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/crypto-monitor.log
    max-size: 10MB
    max-history: 7

# ============================================
# ACTUATOR (MONITORAMENTO)
# ============================================
management:
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: /actuator
  endpoint:
    health:
      show-details: always
  health:
    mail:
      enabled: false
  info:
    env:
      enabled: true

# ============================================
# INFORMAÇÕES DA APLICAÇÃO
# ============================================
info:
  app:
    name: Crypto Monitor
    description: Sistema de Monitoramento de Criptomoedas com Controle por Usuário
    version: 2.0.0
    features:
      - Monitoramento controlado por usuário
      - Alertas personalizados por email
      - Sistema anti-spam de notificações
      - Suporte multi-usuário
  java:
    version: "17.0.16"
  build:
    timestamp: ${TIMESTAMP}